title: My Blog
author: Underzated
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  An indian guy goes on a journey to find the truest meaning of life. Going through cultural identity crisis to being yourself. Everything in one place :)

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
